/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsSessionOptions {
  /** 单次超时(ms)，默认 2000 */
  timeout?: number
  /** 重试次数，默认 1 */
  retries?: number
  /** TTL，默认 128 */
  ttl?: number
  /** payload 大小(bytes)，默认 64 */
  packetSize?: number
}
export interface JsPingReply {
  addr: string
  seq: number
  ttl: number
  /** RTT in milliseconds */
  time: number
  bytes: number
}
export interface JsPingTimeout {
  seq: number
  target: string
}
export interface JsPingError {
  seq: number
  target: string
  icmpType: number
  icmpCode: number
}
export declare class NativePingSession {
  /**
   * 创建 PingSession
   *
   * `on_event` 回调在收到回包/超时/错误时触发。
   * JS 层根据事件类型分发到对应的 handler。
   */
  constructor(options: JsSessionOptions | undefined | null, onReply: (err: Error | null, arg: JsPingReply) => any, onTimeout: (err: Error | null, arg: JsPingTimeout) => any, onError: (err: Error | null, arg: JsPingError) => any)
  /** 发送 ping 请求，返回 sequence number */
  sendPing(target: string): number
  /** 获取当前 pending 请求数量 */
  pendingCount(): number
  /** 关闭 session */
  close(): void
}
